version: '3.8'

volumes:
  postgres_data:


services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: /start


