version: '3.7'

services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
      target: production
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start


