.layers: &default_layers
#  - arn:aws:lambda:us-east-1:027255383542:layer:AWS-AppConfig-Extension:69
  - arn:aws:lambda:us-east-1:347599033421:layer:amazon_linux_fonts:1
  - Ref: PythonRequirementsLambdaLayer

dev:
  layers: *default_layers
prod:
  layers: *default_layers
