import os

TEMPLATE_TABLE = os.getenv('TEMPLATE_TABLE')
REPLACEMENT_TABLE = os.getenv('REPLACEMENT_TABLE')
CERTIFICATE_TABLE = os.getenv('CERTIFICATE_TABLE')
CERTIFICATE_BUCKET = os.getenv('CERTIFICATE_BUCKET')
CLOUDFRONT_BASE_URL = os.getenv('CLOUDFRONT_BASE_URL')
